name: Merge

on:
  workflow_call:
    inputs:
      target_branch_name:
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check whether base branch name matches target branch name
        run: |
          base_branch_name=$(gh pr view ${{ github.event.pull_request.number }} --json baseRefName --jq .baseRefName)
          if [ "$base_branch_name" != "${{ inputs.target_branch_name }}" ]; then
            echo 'This pull request cannot be merged because the base branch ($base_branch_name) does not match the target branch (${{ inputs.target_branch_name }}).'
            exit 1
          fi

      - name: Merge pull request
        run: |
          if gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name' | grep -q "don't squash"; then
            gh pr merge ${{ github.event.pull_request.number }} --rebase
          else
            gh pr merge ${{ github.event.pull_request.number }} --squash
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
