name: Merge to DEV release branch

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  merge-to-dev-release-branch:
    if: contains(github.event.pull_request.labels.*.name, 'ready for dev testing')
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: ./.github/workflows/merge-pull-request.yml
        with:
          branch_name: 'release/dev'

      - name: Create pull request
        uses: ./.github/workflows/create-pull-request.yml
        with:
          branch_name: 'release/dev'
